FROM maven:3.6-jdk-8-alpine AS MAVEN_TOOL_CHAIN
COPY TeaStore-dockerStudy /tmp/
WORKDIR /tmp/
#COPY .m2 /root/.m2
RUN mvn clean install -DskipTests
 
FROM tomcat:9.0-jre8-alpine
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY manager.context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
COPY host-manager.context.xml /usr/local/tomcat/webapps/host-manager/META-INF/context.xml
COPY context-webui.xml /usr/local/tomcat/conf/context.xml
COPY --from=MAVEN_TOOL_CHAIN /tmp/services/tools.descartes.teastore.webui/target/tools.descartes.teastore.webui.war $CATALINA_HOME/webapps/tools.descartes.teastore.webui.war
